### PR TITLE
fix(kms-local): replace buggy didcomm clone with did jwt implementation

### LINKED ISSUE #306: keyManagerEncryptJWE allegedly fails in sendMessageDIDCommAlpha1
**Describe the bug**
I am trying to send an encrypted DIDComm message (type: jwt respectively sdr) to a messaging endpoint. When I look at the message content, I see that it is not the encrypted postPayload I was expecting. When I run my code with the DEBUG=* I see that the function keyManagerEncryptJWE inside the function sendMessageDIDCommAlpha1 is being invoked. This means there are encryption keys on both sides available. However, when I look at the console output I see the following:
```bash
  daf:agent:resolveDid:result { '@context': 'https://w3id.org/did/v1', id: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e', publicKey: [ { id: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e#controller', type: 'Secp256k1VerificationKey2018', controller: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e', ethereumAddress: '0xad804e93f8454f3d157403e82aa4d512cb88647e' }, { id: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e#delegate-1', type: 'Ed25519VerificationKey2018', controller: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e', publicKeyHex: 'cf0c02fc41f0c3c080b53af04c9a93035a087035044f221ea0a1b0465d912741' } ], authentication: [ { type: 'Secp256k1SignatureAuthentication2018', publicKey: 'did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e#controller' } ], service: [ { type: 'Messaging', serviceEndpoint: 'http://localhost:3332/messaging' } ] } +0ms
  daf:agent:identityManagerGetIdentity { did: 'did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e' } +0ms
  daf:agent:identityManagerGetIdentity:result { did: 'did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e', controllerKeyId: '04641cc710edebd84ce120ed2563a77437369190c3b4043d66820cb783db8fbabdc980cd635923b1b827a955a6c25e32995ac4410b09abf10a15856b721809fdcd', provider: 'did:ethr:goerli', services: [ Service { id: 'did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e#msg', type: 'Messaging', serviceEndpoint: 'http://localhost:3001/messaging', description: 'Handles incoming POST messages' } ], keys: [ { kid: '04641cc710edebd84ce120ed2563a77437369190c3b4043d66820cb783db8fbabdc980cd635923b1b827a955a6c25e32995ac4410b09abf10a15856b721809fdcd', type: 'Secp256k1', kms: 'local', publicKeyHex: '04641cc710edebd84ce120ed2563a77437369190c3b4043d66820cb783db8fbabdc980cd635923b1b827a955a6c25e32995ac4410b09abf10a15856b721809fdcd' }, { kid: '9f7ec2f87e69eb487ac5d13fd02bf9e006425e6cc359f3163b1790318eb74a5f', type: 'Ed25519', kms: 'local', publicKeyHex: '9f7ec2f87e69eb487ac5d13fd02bf9e006425e6cc359f3163b1790318eb74a5f' } ], alias: 'verifier' } +0ms
  daf:agent:keyManagerEncryptJWE { kid: '9f7ec2f87e69eb487ac5d13fd02bf9e006425e6cc359f3163b1790318eb74a5f', to: { type: 'Ed25519', publicKeyHex: 'cf0c02fc41f0c3c080b53af04c9a93035a087035044f221ea0a1b0465d912741', kid: 'cf0c02fc41f0c3c080b53af04c9a93035a087035044f221ea0a1b0465d912741' }, data: '{"from":"did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e","to":"did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e","type":"jwt","body":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE2MDgxNDU3MDAsInR5cGUiOiJzZHIiLCJjbGFpbXMiOlt7Imlzc3VlcnMiOlt7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDA1MDFjZGRkNjkzMDcwNGJkMjFiMjM2MTNkYzE5MzNkYzk1MGIzYTkiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifSx7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDUyMzMyZjhjNmUwOTM5NDgxM2U2N2M1NjcyZWU2MjIxOWQzNDI4ZDYiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMCJ9XSwiY2xhaW1UeXBlIjoibmFtZSIsImVzc2VudGlhbCI6dHJ1ZSwicmVhc29uIjoiUmVxdWlyZWQgZm9yIEF1dGhlbnRpY2F0aW9uIn1dLCJzdWJqZWN0IjoiZGlkOmV0aHI6Z29lcmxpOjB4YWQ4MDRlOTNmODQ1NGYzZDE1NzQwM2U4MmFhNGQ1MTJjYjg4NjQ3ZSIsImNyZWRlbnRpYWxzIjpbImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSkZVekkxTmtzaWZRLmV5SjJZeUk2ZXlKamNtVmtaVzUwYVdGc1UzVmlhbVZqZENJNmV5SnVZVzFsSWpvaVZtVnlhV1pwWlhJaWZTd2lRR052Ym5SbGVIUWlPbHNpYUhSMGNITTZMeTkzZDNjdWR6TXViM0puTHpJd01UZ3ZZM0psWkdWdWRHbGhiSE12ZGpFaVhTd2lkSGx3WlNJNld5SldaWEpwWm1saFlteGxRM0psWkdWdWRHbGhiQ0lzSWxCeWIyWnBiR1VpWFgwc0ltTnlaV1JsYm5ScFlXeFRkR0YwZFhNaU9uc2lkSGx3WlNJNklrVjBhSEpUZEdGMGRYTlNaV2RwYzNSeWVUSXdNVGtpTENKcFpDSTZJbkpwYm10bFluazZNSGc1TjJaa01qYzRPVEpqWkdORU1ETTFaRUZsTVdabE56RXlNelZqTmpNMk1EUTBRalU1TXpRNEluMHNJbk4xWWlJNkltUnBaRHBsZEdoeU9tZHZaWEpzYVRvd2VEWTFOV0kwWXpJeFpUa3paRFZqWVdGbVpUVTNPV0kwTW1ZNVpUSmhZV0U1TXpSalpEZGlNV1VpTENKdVltWWlPakUyTURjMk56ZzNOemtzSW1semN5STZJbVJwWkRwbGRHaHlPbWR2WlhKc2FUb3dlREExTURGalpHUmtOamt6TURjd05HSmtNakZpTWpNMk1UTmtZekU1TXpOa1l6azFNR0l6WVRraWZRLmw5enVTcllaTXBXalJrT1V0ZTJmZUoxdndEQjlMamhJZF9sRXdHVHNwUEh3OHUzMUdWdWhTVHJ5Z1NiMk9WZUwxRS1YQ2l2SkQ1ZHJEVlVsVTJlbVFRIl0sImlzcyI6ImRpZDpldGhyOmdvZXJsaToweDY1NWI0YzIxZTkzZDVjYWFmZTU3OWI0MmY5ZTJhYWE5MzRjZDdiMWUifQ.L0fcjwi7sGFTsuZ67Yxtp2gz8RshlsJx-Z1UIPfJqy9IzCbaEvdYyjNYA_yESWgLYgV0aTlupKWUsESFuayf-AA","id":"62ee7452-328b-4014-bc6f-e94eb04b8b31"}' } +0ms
  daf:did-comm:action-handler Sending to http://localhost:3332/messaging +2s
  daf:did-comm:action-handler Status 200 OK +2s
  daf:agent:handleMessage { raw: '{"from":"did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e","to":"did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e","type":"jwt","body":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE2MDgxNDU3MDAsInR5cGUiOiJzZHIiLCJjbGFpbXMiOlt7Imlzc3VlcnMiOlt7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDA1MDFjZGRkNjkzMDcwNGJkMjFiMjM2MTNkYzE5MzNkYzk1MGIzYTkiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifSx7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDUyMzMyZjhjNmUwOTM5NDgxM2U2N2M1NjcyZWU2MjIxOWQzNDI4ZDYiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMCJ9XSwiY2xhaW1UeXBlIjoibmFtZSIsImVzc2VudGlhbCI6dHJ1ZSwicmVhc29uIjoiUmVxdWlyZWQgZm9yIEF1dGhlbnRpY2F0aW9uIn1dLCJzdWJqZWN0IjoiZGlkOmV0aHI6Z29lcmxpOjB4YWQ4MDRlOTNmODQ1NGYzZDE1NzQwM2U4MmFhNGQ1MTJjYjg4NjQ3ZSIsImNyZWRlbnRpYWxzIjpbImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSkZVekkxTmtzaWZRLmV5SjJZeUk2ZXlKamNtVmtaVzUwYVdGc1UzVmlhbVZqZENJNmV5SnVZVzFsSWpvaVZtVnlhV1pwWlhJaWZTd2lRR052Ym5SbGVIUWlPbHNpYUhSMGNITTZMeTkzZDNjdWR6TXViM0puTHpJd01UZ3ZZM0psWkdWdWRHbGhiSE12ZGpFaVhTd2lkSGx3WlNJNld5SldaWEpwWm1saFlteGxRM0psWkdWdWRHbGhiQ0lzSWxCeWIyWnBiR1VpWFgwc0ltTnlaV1JsYm5ScFlXeFRkR0YwZFhNaU9uc2lkSGx3WlNJNklrVjBhSEpUZEdGMGRYTlNaV2RwYzNSeWVUSXdNVGtpTENKcFpDSTZJbkpwYm10bFluazZNSGc1TjJaa01qYzRPVEpqWkdORU1ETTFaRUZsTVdabE56RXlNelZqTmpNMk1EUTBRalU1TXpRNEluMHNJbk4xWWlJNkltUnBaRHBsZEdoeU9tZHZaWEpzYVRvd2VEWTFOV0kwWXpJeFpUa3paRFZqWVdGbVpUVTNPV0kwTW1ZNVpUSmhZV0U1TXpSalpEZGlNV1VpTENKdVltWWlPakUyTURjMk56ZzNOemtzSW1semN5STZJbVJwWkRwbGRHaHlPbWR2WlhKc2FUb3dlREExTURGalpHUmtOamt6TURjd05HSmtNakZpTWpNMk1UTmtZekU1TXpOa1l6azFNR0l6WVRraWZRLmw5enVTcllaTXBXalJrT1V0ZTJmZUoxdndEQjlMamhJZF9sRXdHVHNwUEh3OHUzMUdWdWhTVHJ5Z1NiMk9WZUwxRS1YQ2l2SkQ1ZHJEVlVsVTJlbVFRIl0sImlzcyI6ImRpZDpldGhyOmdvZXJsaToweDY1NWI0YzIxZTkzZDVjYWFmZTU3OWI0MmY5ZTJhYWE5MzRjZDdiMWUifQ.L0fcjwi7sGFTsuZ67Yxtp2gz8RshlsJx-Z1UIPfJqy9IzCbaEvdYyjNYA_yESWgLYgV0aTlupKWUsESFuayf-AA","id":"62ee7452-328b-4014-bc6f-e94eb04b8b31"}', metaData: [ { type: 'DIDComm-sent' } ], save: true } +0ms
```
I suppose the method keyManagerEncryptJWE fails somehow and the program continues with the plain text payload (look at the handleMessage arguments). But I cannot see why.

**Steps To Reproduce**
I tried some manual encrypting with the DAF CLI using the same arguments except that I switched the Key IDs:
```bash
martin@workhorse:~/Documents/daf-cli$ daf execute -m keyManagerEncryptJWE -f encrypt_args.json
{ argsFile: 'encrypt_args.json' }

Method:  keyManagerEncryptJWE

Arguments:  {
  "kid": "cf0c02fc41f0c3c080b53af04c9a93035a087035044f221ea0a1b0465d912741",
  "to": {
    "type": "Ed25519",
    "publicKeyHex": "9f7ec2f87e69eb487ac5d13fd02bf9e006425e6cc359f3163b1790318eb74a5f",
    "kid": "9f7ec2f87e69eb487ac5d13fd02bf9e006425e6cc359f3163b1790318eb74a5f"
  },
  "data": "{\"from\":\"did:ethr:goerli:0x655b4c21e93d5caafe579b42f9e2aaa934cd7b1e\",\"to\":\"did:ethr:goerli:0xad804e93f8454f3d157403e82aa4d512cb88647e\",\"type\":\"jwt\",\"body\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE2MDgxNDU3MDAsInR5cGUiOiJzZHIiLCJjbGFpbXMiOlt7Imlzc3VlcnMiOlt7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDA1MDFjZGRkNjkzMDcwNGJkMjFiMjM2MTNkYzE5MzNkYzk1MGIzYTkiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifSx7ImRpZCI6ImRpZDpldGhyOmdvZXJsaToweDUyMzMyZjhjNmUwOTM5NDgxM2U2N2M1NjcyZWU2MjIxOWQzNDI4ZDYiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMCJ9XSwiY2xhaW1UeXBlIjoibmFtZSIsImVzc2VudGlhbCI6dHJ1ZSwicmVhc29uIjoiUmVxdWlyZWQgZm9yIEF1dGhlbnRpY2F0aW9uIn1dLCJzdWJqZWN0IjoiZGlkOmV0aHI6Z29lcmxpOjB4YWQ4MDRlOTNmODQ1NGYzZDE1NzQwM2U4MmFhNGQ1MTJjYjg4NjQ3ZSIsImNyZWRlbnRpYWxzIjpbImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSkZVekkxTmtzaWZRLmV5SjJZeUk2ZXlKamNtVmtaVzUwYVdGc1UzVmlhbVZqZENJNmV5SnVZVzFsSWpvaVZtVnlhV1pwWlhJaWZTd2lRR052Ym5SbGVIUWlPbHNpYUhSMGNITTZMeTkzZDNjdWR6TXViM0puTHpJd01UZ3ZZM0psWkdWdWRHbGhiSE12ZGpFaVhTd2lkSGx3WlNJNld5SldaWEpwWm1saFlteGxRM0psWkdWdWRHbGhiQ0lzSWxCeWIyWnBiR1VpWFgwc0ltTnlaV1JsYm5ScFlXeFRkR0YwZFhNaU9uc2lkSGx3WlNJNklrVjBhSEpUZEdGMGRYTlNaV2RwYzNSeWVUSXdNVGtpTENKcFpDSTZJbkpwYm10bFluazZNSGc1TjJaa01qYzRPVEpqWkdORU1ETTFaRUZsTVdabE56RXlNelZqTmpNMk1EUTBRalU1TXpRNEluMHNJbk4xWWlJNkltUnBaRHBsZEdoeU9tZHZaWEpzYVRvd2VEWTFOV0kwWXpJeFpUa3paRFZqWVdGbVpUVTNPV0kwTW1ZNVpUSmhZV0U1TXpSalpEZGlNV1VpTENKdVltWWlPakUyTURjMk56ZzNOemtzSW1semN5STZJbVJwWkRwbGRHaHlPbWR2WlhKc2FUb3dlREExTURGalpHUmtOamt6TURjd05HSmtNakZpTWpNMk1UTmtZekU1TXpOa1l6azFNR0l6WVRraWZRLmw5enVTcllaTXBXalJrT1V0ZTJmZUoxdndEQjlMamhJZF9sRXdHVHNwUEh3OHUzMUdWdWhTVHJ5Z1NiMk9WZUwxRS1YQ2l2SkQ1ZHJEVlVsVTJlbVFRIl0sImlzcyI6ImRpZDpldGhyOmdvZXJsaToweDY1NWI0YzIxZTkzZDVjYWFmZTU3OWI0MmY5ZTJhYWE5MzRjZDdiMWUifQ.L0fcjwi7sGFTsuZ67Yxtp2gz8RshlsJx-Z1UIPfJqy9IzCbaEvdYyjNYA_yESWgLYgV0aTlupKWUsESFuayf-AA\",\"id\":\"62ee7452-328b-4014-bc6f-e94eb04b8b31\"}"
}
incomplete input
```

I am a little lost with this error message.

**Expected behaviour**
I expect a JWE postPayload after the execution of keyManagerEncryptJWE instead of a plain text DIDComm message.

**Versions:**
 - Daf: 7.0.0-beta.49
 - Daf-cli: 7.0.0-beta.49

### LINKED ISSUE #538: replace bootleg didcomm-js with `createJWE` from `did-jwt`
The current implementation is antiquated and its correctness cannot be proven.
There is already an implementation of anonymous encryption in `did-jwt` and work in progress to [add authenticated encryption](https://github.com/decentralized-identity/did-jwt/pull/177).
This should be used instead.

### PR DESCRIPTION
**Pull request by mirceanis**
This fixes an old bug that was causing incorrect didcomm messaging in veramo.
The `kms-local` plugin now uses the [`did-jwt`](https://github.com/decentralized-identity/did-jwt/) implementation of JWE using the anon [de]encrypter.

* [X] check if the current `kms-local` plugin can be used in a react-native context.
It works fine. Don't forget to add `@ethersproject/shims`.
* [X] remove the `libsodium-wrappers` dependency and replaces it with [`@stablelib/*`](https://github.com/StableLib/stablelib) which should make it easier to work with multiple JS environments.
* [X] BREAKING CHANGE: remove `kms-local-react-native`. Use `kms-local` instead.

fixes #538
probably also fixes #306

### CODE REVIEW

File: packages/key-manager/src/key-manager.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export class KeyManager implements IAgentPlugin {
       keyManagerGet: this.keyManagerGet.bind(this),
       keyManagerDelete: this.keyManagerDelete.bind(this),
       keyManagerImport: this.keyManagerImport.bind(this),
-      keyManagerEncryptJWE: this.keyManagerDecryptJWE.bind(this),
```
Comment (mirceanis) [inline packages/key-manager/src/key-manager.ts:44]: Oooohweee, what a typo!!
This is likely the culprit of #306

**Review by awoie — APPROVED** [review]
lgtm
