### PR TITLE
fix: didcomm message handler should attempt to pass message to other handlers

### LINKED ISSUE #944: DIDComm message handler breaks out of message handler flow
Once a DIDComm v2 message is unpacked, no further messageHandlers are executed. Maybe this is intended behavior, but I was expecting to use subsequent message handlers to perform more processing on the message.

The fix would be easy, changing line 124 of the DidComm message-handler.ts from "return message" to "return super.handle(message, context)".

### PR DESCRIPTION
**Pull request by nickreynolds**
## What issue is this PR fixing

fixes #944

## What is being changed
DIDComm Message Handler should attempt to forward message to downstream handlers (but should not fail if none handle message)

## Quality
Check all that apply:
* [X] I want these changes to be integrated
* [X] I successfully ran `yarn`, `yarn build`, `yarn test`, `yarn test:browser` locally.
* [ ] I allow my PR to be updated by the reviewers (to speed up the review process).
* [ ] I added unit tests.
* [X] I added integration tests.
* [ ] I did not add automated tests because _________, and I am aware that a PR without tests will likely get rejected.

### CODE REVIEW

File: __tests__/shared/didCommAndDataStoreWithCredentials.ts [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+      const verifiableCredential = await vc(creator, 'lds')
+      const packedMessage = await packed(verifiableCredential)
+
+      await agent.sendDIDCommMessage({        
+        messageId: 'test-jwt-success',
+        packedMessage,
+        recipientDidUrl: sender.did,
+      })
+      const messages = await agent.dataStoreORMGetMessagesCount({})
+      expect(messages).toEqual(2)
```
Comment (mirceanis) [inline __tests__/shared/didCommAndDataStoreWithCredentials.ts:151]: testing message flow by count is prone to some weird test failures when multiple tests produce messages.

It would be better to use message IDs, or something else to check if they get processed correctly.

**Review by mirceanis — CHANGES_REQUESTED** [review]
This is a very nice fix that also doesn't introduce a breaking change, which I would have expected for #944. Great work!

The test cases can be improved a little bit; please see my comments.
